url:
baseurl:

# Site settings
title: O.D.I.N.
email: your-email@domain.com
description: "We do stuff."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mayank Badola
  pic: https://avatars2.githubusercontent.com/u/8503331?v=3&s=400
  position: Founder
  social:
    - title: twitter
      url: https://twitter.com/mbad0la
    - title: github
      url: http://mbad0la.github.io

- name: Divjot Singh
  pic: https://avatars2.githubusercontent.com/u/6177621?v=3&s=400
  position: Org Core Member
  social:
    - title: twitter
      url: https://twitter.com/bogas04
    - title: github
      url: http://bogas04.github.io

- name: Tarasha Khurana
  pic: https://avatars2.githubusercontent.com/u/12378485?v=3&s=400
  position: Collaborator
  social:
    - title: github
      url: https://github.com/tarashakhurana

- name: Karanbir Chahal
  pic: https://avatars2.githubusercontent.com/u/13203966?v=3&s=400
  position: Collaborator
  social:
    - title: github
      url: https://github.com/karanchahal

- name: Aman Priyadarshi
  pic: https://avatars3.githubusercontent.com/u/10295295?v=3&s=400
  position: Collaborator
  social:
    - title: twitter
      url: https://twitter.com/amaneureka
    - title: github
      url: http://github.com/amaneureka

- name: Rahul Khanna
  pic: https://avatars0.githubusercontent.com/u/11595304?v=3&s=400
  position: Collaborator
  social:
    - title: github
      url: https://github.com/zerismo


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/o-d-i-n

# Postal address (add as many lines as necessary)
address:
  - line: NSIT, Dwarka Sector 3
  - line: New Delhi, 110075

# Build settings
markdown: kramdown
permalink: pretty
